---
title: "Day 8: Playground"
author: AndiF
date: 10 Dec 2025
output: 
  html_notebook: 
    code_folding: none
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tictoc)
library(beepr)
library(igraph)
options(scipen = 999)
```


```{r}
coords <- read.csv("aoc08.txt", header = FALSE)
names(coords) <- c("x", "y", "z")
head(coords)
```


```{r}
pair_dat <- combn(nrow(coords), 2) |> t() |> as.data.frame()
names(pair_dat) <- c("i", "j")
dim(pair_dat)
```

```{r}
head(pair_dat)
```


```{r}
euc <- function(dat, i, j) {
  x <- dat[i,] |> as.vector()
  y <- dat[j,] |> as.vector()
  rbind(x, y) |> dist() |> as.vector()
}
```



```{r}
euc(coords, 1, 2)
```

```{r}
tic()
pair_dat$dist <- mapply(\(x,y) euc(coords, x, y), pair_dat$i, pair_dat$j)
toc()
beep(2)
```

```{r}
sorted_pairs <- pair_dat |>
  arrange(dist)
sorted_pairs
```


```{r}
edge_mat <- sorted_pairs[,c("i", "j")] |> head(1000) |> as.matrix()
the_graph <- graph_from_edgelist(edge_mat, directed = FALSE)
```

```{r}
comps <- the_graph |> components(mode = "weak")
sort(comps$csize) |> rev() |> head(3) |> prod()
```

## Part 2

```{r}
big_mat <- sorted_pairs[,c("i", "j")] |> as.matrix()
head(big_mat)
```


```{r}
tic()
growing_g <- make_empty_graph(n = 1000, directed = FALSE)
done <- FALSE
i <- 1

while (!done) {
  growing_g <- growing_g |> add_edges(big_mat[i,])
  comps <- growing_g |> components(mode = "weak")
  
  if (comps$no == 1)
    done <- TRUE
  else
    i <- i + 1
}
toc()
```

```{r}
last_two <- big_mat[i,] |> as.vector()
last_two
```


```{r}
coords[last_two,] |> pull(x) |> prod()
```


