---
title: "Day 3: Lobby"
author: AndiF
date: 2 Dec 2025
output: 
  html_notebook: 
    code_folding: none
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tictoc)
library(gmp)
```


Trying *read_lines* for a change:

```{r}
dat <- read_lines("aoc03.txt") |> strsplit("") |> map(as.numeric) 
dat[1:3]
```


Is this bruteforcible...?

```{r}
length(dat)
```

```{r}
length(dat[[1]])
```

```{r}
choose(100, 2)
```

```{r}
choose(100, 2) * 200
```

Sure.


Check I remember how *combn* works...

```{r}
combn(c("z", "b", "w"), 2, print)
```

Hurrah -- it returns the elements in the order I want.


Try it with an example or two:

```{r}
test_xs <- dat[[3]]
test_xs
```


```{r}
combn(test_xs, 2, \(ys) ys[1] * 10 + ys[2]) |> max()
```


## Part 1

Let's just do it.


```{r}
arrange_row <- function(xs)
  combn(xs, 2, \(ys) ys[1] * 10 + ys[2]) |> max()
```


```{r}
tic()
res <- map_dbl(dat, arrange_row)
toc()
```

```{r}
sum(res)
```

Correct.


## Part 2


Time to move to {gmp}

```{r}
987654321111 + 811111111119 + 434234234278 + 888911112111
```


```{r}
c("987654321111", "811111111119", "434234234278", "888911112111") |>
  as.bigz() |>
  sum()
```

Also brute force isn't going to work:

```{r}
choose(100, 12)
```


Recursion time:

```{r}
find_max_seq <- function(xs, k) {
  stopifnot(k >= 1)
  res <- NA
  end_search <- length(xs) - (k - 1)
  
  #cat("xs: ")
  #print(xs)
  #cat("k: ")
  #print(k)
  #cat("end_search: ")
  #print(end_search)
  
  search_xs <- xs[1:end_search]
  #cat("search_xs: ")
  #print(search_xs)
  
  if (k == 1) {
    res <- max(search_xs)
  }
  else {
    max_pos <- which.max(search_xs)[1]
    the_max <- search_xs[max_pos]
    next_search_xs <- xs[(max_pos + 1):length(xs)]
    res <- c(the_max, find_max_seq(next_search_xs, k - 1))
  }
  
  res
}
```


```{r}
find_max_seq_chr <- function(xs, k) {
  find_max_seq(xs, k) |> paste(collapse = "")
}

find_max_seq_chr(test_xs, 2)
```


```{r}
tic()
res2 <- map_chr(dat, \(xs) find_max_seq_chr(xs, 12)) |> as.bigz()
toc()
```

```{r}
res2
```

```{r}
sum(res2)
```



